// 由《游戏数据速查.md》同步；该文档是具体游戏数据的唯一权威来源。
window.GAME_DATA = {
  source: "游戏数据速查.md",
  heroes: [
    { name: "甄姬", faction: "魏", tier: 1, attack: 1, health: 1, skill: "[洛神] 武将被召唤时，使其 +（1）攻击力" },
    { name: "庞德", faction: "魏", tier: 1, attack: 2, health: 2, skill: "[殉节] 阵亡时，使后方最近的友军 +（1/1）" },
    { name: "马岱", faction: "蜀", tier: 1, attack: 2, health: 3, skill: "[伏斩] 击杀后，获得（1）经验值" },
    { name: "廖化", faction: "蜀", tier: 1, attack: 2, health: 2, skill: "[宿将] 友军获得经验值时，使其 +（1）生命值" },
    { name: "马云禄", faction: "蜀", tier: 1, attack: 2, health: 2, skill: "[西凉烈女] 战斗开始时，获得（1）经验值" },
    { name: "诸葛瑾", faction: "吴", tier: 1, attack: 1, health: 3, skill: "[弘雅] 敌军获得负面状态时，使随机1名其他友军 +（1/1）" },
    { name: "韩当", faction: "吴", tier: 1, attack: 2, health: 3, skill: "[勇烈] 攻击后，对随机敌军造成（1）点伤害和灼烧" },
    { name: "华雄", faction: "群", tier: 1, attack: 3, health: 2, skill: "[骁勇] 战斗开始时，对最前方（1）名敌军造成2点伤害" },
    { name: "陈宫", faction: "群", tier: 1, attack: 1, health: 2, skill: "[百计多谋] 被招募时，对随机武将使用1张（1）阶计策" },
    { name: "左慈", faction: "无", tier: 1, attack: 3, health: 1, skill: "[变幻莫测] 出售时，交换前后两名（2）阶及以下、彼此拥有相同羁绊武将的最终面板攻击和生命值" },
    { name: "夏侯渊", faction: "魏", tier: 2, attack: 3, health: 2, skill: "[千里奔袭] 攻击后，召唤1名（LV1）2/1骑兵" },
    { name: "于禁", faction: "魏", tier: 2, attack: 1, health: 2, skill: "[军纪严明] 回合结束时，使前方最近的（1）名武将 +1/1" },
    { name: "魏延", faction: "蜀", tier: 2, attack: 2, health: 4, skill: "[才高气烈] 友军获得经验值时，自身 +（1）攻击力" },
    { name: "黄忠", faction: "蜀", tier: 2, attack: 2, health: 3, skill: "[老当益壮] 回合结束时，使自己获得（1）经验值" },
    { name: "程普", faction: "吴", tier: 2, attack: 2, health: 3, skill: "[元勋] 被招募时，使前方最近的武将 +（1/1）" },
    { name: "小乔", faction: "吴", tier: 2, attack: 1, health: 2, skill: "[花容月貌] 前方最近的武将攻击后，使其 +（2）生命值" },
    { name: "黄盖", faction: "吴", tier: 2, attack: 2, health: 4, skill: "[苦肉计] 受伤时，使随机（1）名敌军获得灼烧" },
    { name: "颜良", faction: "群", tier: 2, attack: 3, health: 3, skill: "[勇冠三军] 自身羁绊武将被招募后，使自己 +（1/1）" },
    { name: "汉献帝", faction: "群", tier: 2, attack: 1, health: 1, skill: "[飘摇] 我军羁绊等级发生变化时，使随机1名其他友军 +（1/1）" },
    { name: "貂蝉", faction: "无", tier: 2, attack: 2, health: 1, skill: "[倾城] 回合结束时，复制前方最近武将的羁绊，并使其 +（1）生命值" },
    { name: "夏侯惇", faction: "魏", tier: 3, attack: 3, health: 5, skill: "[刚勇] 受伤时，使随机（1）名其他自身羁绊武将 +（2/2）" },
    { name: "乐进", faction: "魏", tier: 3, attack: 3, health: 3, skill: "[先登陷阵] 攻击前，在身前召唤2名（LV1）2/1骑兵" },
    { name: "徐晃", faction: "魏", tier: 3, attack: 4, health: 4, skill: "[长驱直入] 战斗开始时，对最后方敌军造成2次（3）点伤害" },
    { name: "张飞", faction: "蜀", tier: 3, attack: 4, health: 4, skill: "[燕人咆哮] 攻击前，使目标敌军攻击力 -（3）" },
    { name: "徐庶", faction: "蜀", tier: 3, attack: 3, health: 3, skill: "[荐才] 战斗开始时，使前方最近的武将获得（1）经验值" },
    { name: "太史慈", faction: "吴", tier: 3, attack: 5, health: 3, skill: "[箭无虚发] 战斗开始时，对生命值最高的敌军造成（3）点伤害和灼烧" },
    { name: "周泰", faction: "吴", tier: 3, attack: 3, health: 3, skill: "[肉身铁壁] 攻击时，受到的伤害减少（3）点" },
    { name: "鲁肃", faction: "吴", tier: 3, attack: 3, health: 3, skill: "[联合] 回合开始时，每存在2个阵容羁绊，获得（2）金币" },
    { name: "文丑", faction: "群", tier: 3, attack: 2, health: 4, skill: "[悍勇] 战斗开始阶段，友军每次造成伤害，使自己 +（1/1）" },
    { name: "于吉", faction: "无", tier: 3, attack: 3, health: 2, skill: "[蛊惑] 我军羁绊等级降低时，使前方最近的友军 +（1/1）" },
    { name: "荀攸", faction: "魏", tier: 4, attack: 4, health: 2, skill: "[奇策] 战斗中，自身羁绊武将被召唤时，使其获得（2）经验值" },
    { name: "典韦", faction: "魏", tier: 4, attack: 6, health: 6, skill: "[古之恶来] 战斗开始时，吞噬前方最近的友军，并在阵亡后将其以（LV1）释放" },
    { name: "赵云", faction: "蜀", tier: 4, attack: 6, health: 6, skill: "[龙胆] 升级时，获得“无双”，并使自己 +（2/2）。无双：免疫负面状态；攻击后，对目标后方最近的1个单位造成本次伤害的30%" },
    { name: "法正", faction: "蜀", tier: 4, attack: 4, health: 3, skill: "[以逸待劳] 友军升级时，使其额外获得（1）经验值和“休整”。休整：友军攻击时，自身 +（2）生命值" },
    { name: "孙策", faction: "吴", tier: 4, attack: 5, health: 5, skill: "[江东霸王] 战斗开始时，每存在1名自身羁绊武将，自身 +（1/2）" },
    { name: "凌统", faction: "吴", tier: 4, attack: 4, health: 4, skill: "[国士之风] 自身羁绊武将被招募时，使其 +（2/2）" },
    { name: "吕蒙", faction: "吴", tier: 4, attack: 4, health: 5, skill: "[白衣渡江] 攻击前，使最前方（1）名敌军的技能在本轮无法触发" },
    { name: "公孙瓒", faction: "群", tier: 4, attack: 5, health: 3, skill: "[白马义从] 战斗开始时，摧毁前方最近的（1）名敌军的装备，并造成3点伤害" },
    { name: "张郃", faction: "群", tier: 4, attack: 4, health: 4, skill: "[巧变] 我军羁绊等级发生变化时，使自身 +（2/1）" },
    { name: "司马徽", faction: "无", tier: 4, attack: 3, health: 3, skill: "[广识] 每次购买时，选择1名友军为其添加1个额外羁绊，并使其 +（1/1）" },
    { name: "贾诩", faction: "魏", tier: 5, attack: 4, health: 3, skill: "[反间] 战斗开始时，使随机（1）名敌军获得“反间”。反间：阵亡后，在我方以LV1、3/3召唤自身" },
    { name: "郭嘉", faction: "魏", tier: 5, attack: 5, health: 2, skill: "[遗计平辽] 阵亡时，使所有自身羁绊武将 +（2/2）" },
    { name: "张辽", faction: "魏", tier: 5, attack: 7, health: 5, skill: "[威震逍遥] 战斗开始时，使前方最近的（1）名敌军生命值 -40%" },
    { name: "马超", faction: "蜀", tier: 5, attack: 7, health: 5, skill: "[寒枪破阵] 获得经验值时，自身 +（1/1），并对随机1名敌军造成自身攻击力50%的伤害" },
    { name: "庞统", faction: "蜀", tier: 5, attack: 5, health: 4, skill: "[涅槃] 阵亡后，使随机2名其他友军获得（1）经验值" },
    { name: "陆逊", faction: "吴", tier: 5, attack: 5, health: 6, skill: "[火烧连营] 攻击后，对随机敌军施加（3）次灼烧" },
    { name: "甘宁", faction: "吴", tier: 5, attack: 7, health: 5, skill: "[百骑劫营] 战斗开始时，使最后方2名敌军灼烧，并触发（1）次" },
    { name: "袁术", faction: "群", tier: 5, attack: 5, health: 3, skill: "[玉玺] 被招募时，获得并佩戴传国玉玺；自身佩戴传国玉玺时，其阵亡效果额外触发（1）次" },
    { name: "董卓", faction: "群", tier: 5, attack: 6, health: 4, skill: "[暴虐] 回合结束时，击杀随机1名非自身羁绊武将，并使自己 +（3/3）" },
    { name: "华佗", faction: "无", tier: 5, attack: 3, health: 3, skill: "[急救] 前方最近的友军阵亡时，使其以（LV1）、1/1复活" },
    { name: "曹操", faction: "魏", tier: 6, attack: 6, health: 6, skill: "[奸雄] 自身羁绊武将阵亡时，使随机1名其他友军 +（4/4）" },
    { name: "荀彧", faction: "魏", tier: 6, attack: 5, health: 3, skill: "[王佐之才] 自身羁绊武将被召唤时，使其 +（4/4）" },
    { name: "刘备", faction: "蜀", tier: 6, attack: 7, health: 7, skill: "[仁泽] 回合结束时，使前方最近的自身羁绊武将经验值 -1，并使其 +（5/5）" },
    { name: "诸葛亮", faction: "蜀", tier: 6, attack: 5, health: 5, skill: "[运筹] 友军攻击后，使随机（1）名其他友军获得1经验值" },
    { name: "关羽", faction: "蜀", tier: 6, attack: 10, health: 8, skill: "[威震华夏] 攻击后，使最前方（1）名敌军获得“震慑”。震慑：攻击时造成的伤害 -50%" },
    { name: "孙权", faction: "吴", tier: 6, attack: 5, health: 5, skill: "[权衡] 回合结束时，使前方最近的自身羁绊武将 +（5）攻击力，使后方最近的自身羁绊武将 +（5）生命值" },
    { name: "周瑜", faction: "吴", tier: 6, attack: 8, health: 6, skill: "[风助火势] 敌军受到的灼烧和引燃单次伤害额外增加（1）倍" },
    { name: "张角", faction: "群", tier: 6, attack: 10, health: 3, skill: "[五雷轰顶] 战斗开始时，对随机敌军造成自身攻击力（10%）的伤害，触发5次" },
    { name: "吕布", faction: "群", tier: 6, attack: 12, health: 10, skill: "[天下无双] 攻击前，使自己获得（1）倍效果的“无双”。无双：免疫负面状态；攻击后，对目标后方最近的1个单位造成本次伤害的30%" },
    { name: "袁绍", faction: "群", tier: 6, attack: 5, health: 5, skill: "[号令群雄] 自身羁绊武将被招募时，使所有友军 +（1/2）" },
  ],
  items: [
    { name: "演练", category: "计策", targetMode: "unit", tier: 1, cost: 3, skill: "选择1个武将+1/1", effectId: "stratagem.encourage", image: "res/item_icon/stratagem-encourage.png" },
    { name: "口才", category: "计策", targetMode: "unit", tier: 1, cost: 3, skill: "选择1个武将添加1个额外羁绊，持续1回合", effectId: "stratagem.temporary-bond", image: "res/item_icon/stratagem-temporary-bond.png" },
    { name: "令箭", category: "装备", tier: 2, skill: "相同触发条件的技能，优先触发", effectId: "equipment.initiative-flag", image: "res/item_icon/equipment-initiative-flag.png" },
    { name: "兵符", category: "装备", tier: 2, skill: "阵亡后，在己方最前方召唤1名2/1骑兵", effectId: "equipment.cavalry-talisman", image: "res/item_icon/equipment-cavalry-talisman.png" },
    { name: "举贤", category: "计策", targetMode: "lineup", tier: 2, cost: 3, skill: "等级最高的羁绊中，使随机一名武将+(2/1)", effectId: "stratagem.recommend-talent", image: "res/item_icon/stratagem-recommend-talent.png" },
    { name: "绝影", category: "装备", tier: 3, skill: "受到的伤害-2", effectId: "equipment.iron-armor", image: "res/item_icon/equipment-iron-armor.png" },
    { name: "同袍共进", category: "计策", targetMode: "lineup", tier: 3, cost: 3, skill: "等级最高的羁绊中，使随机2名武将+(1/1)", effectId: "stratagem.advance-together", image: "res/item_icon/stratagem-advance-together.png" },
    { name: "潜龙蓄势", category: "计策", targetMode: "lineup", tier: 3, cost: 3, skill: "使未激活羁绊中的所有武将+(1/1)", effectId: "stratagem.hidden-potential", image: "res/item_icon/stratagem-hidden-potential.png" },
    { name: "百厄角", category: "装备", tier: 4, skill: "攻击后，对敌方最前方的单位施加1种随机负面状态", effectId: "equipment.calamity-blade", image: "res/item_icon/equipment-calamity-blade.png" },
    { name: "整军经武", category: "计策", targetMode: "lineup", tier: 4, cost: 3, skill: "选择1个羁绊，使商店中该羁绊下所有武将+2/2", effectId: "stratagem.train-army", image: "res/item_icon/stratagem-train-army.png" },
    { name: "歃血盟书", category: "计策", targetMode: "unit", tier: 4, cost: 3, skill: "选择1个武将，首次购买时为其添加1个额外羁绊；第2次以后选择1个武将使其+3/3", effectId: "stratagem.blood-oath", image: "res/item_icon/stratagem-blood-oath.png" },
    { name: "神农秘典", category: "装备", tier: 5, skill: "获得负面状态或受伤时使自身+2/2", effectId: "equipment.blood-armor", image: "res/item_icon/equipment-blood-armor.png" },
    { name: "传国玉玺", category: "装备", tier: 5, generatedOnly: true, skill: "阵亡时，使商店中自身羁绊武将永久+1/1", effectId: "equipment.imperial-jade-seal", image: "res/item_icon/equipment-imperial-jade-seal.png" },
    { name: "同心戮力", category: "计策", targetMode: "lineup", tier: 5, cost: 3, skill: "使阵容中等级最高的羁绊下所有武将+1/2", effectId: "stratagem.united-force", image: "res/item_icon/stratagem-united-force.png" },
    { name: "开悟", category: "计策", targetMode: "unit", tier: 5, cost: 3, skill: "选择1个武将，经验值+1", effectId: "stratagem.master-guidance", image: "res/item_icon/stratagem-master-guidance.png" },
    { name: "蚩尤古盾", category: "装备", tier: 6, skill: "抵挡10伤害，生效2次", effectId: "equipment.black-tortoise-shield", image: "res/item_icon/equipment-black-tortoise-shield.png" },
    { name: "修罗刀", category: "装备", tier: 6, skill: "攻击伤害+20，生效1次", effectId: "equipment.siege-crossbow", image: "res/item_icon/equipment-siege-crossbow.png" },
    { name: "聚势强军", category: "计策", targetMode: "unit", tier: 6, cost: 3, skill: "选择1个武将，+4/4，每次使用后，下一次额外+1/1", effectId: "stratagem.gather-strength", image: "res/item_icon/stratagem-gather-strength.png" },
  ],
};

// 稳定的结构化武将技能 ID。技能描述只负责展示，实际结算由 app.js 的效果定义驱动。
const HERO_SKILL_EFFECT_IDS = {
  甄姬: "hero.zhenji.luoshen",
  庞德: "hero.pangde.xunjie",
  马岱: "hero.madai.fuzhan",
  廖化: "hero.liaohua.sujiang",
  马云禄: "hero.mayunlu.xiliang-lienv",
  诸葛瑾: "hero.zhugejin.hongya",
  韩当: "hero.handang.yonglie",
  华雄: "hero.huaxiong.xiaoyong",
  陈宫: "hero.chengong.baiji-duomou",
  左慈: "hero.zuoci.bianhuan-moce",
  夏侯渊: "hero.xiahouyuan.qianli-benxi",
  于禁: "hero.yujin.junji-yanming",
  魏延: "hero.weiyan.caigao-qilie",
  黄忠: "hero.huangzhong.laodang-yizhuang",
  程普: "hero.chengpu.yuanxun",
  小乔: "hero.xiaoqiao.huaron-yuemao",
  黄盖: "hero.huanggai.kurouji",
  颜良: "hero.yanliang.yongguan-sanjun",
  汉献帝: "hero.hanxiandi.piaoyao",
  貂蝉: "hero.diaochan.qingcheng",
  夏侯惇: "hero.xiahoudun.gangyong",
  乐进: "hero.yuejin.xiandeng-xianzhen",
  徐晃: "hero.xuhuang.changqu-zhiru",
  张飞: "hero.zhangfei.yanren-paoxiao",
  徐庶: "hero.xushu.jiancai",
  太史慈: "hero.taishici.jianwu-xufa",
  周泰: "hero.zhoutai.roushen-tiebi",
  鲁肃: "hero.lusu.lianhe",
  文丑: "hero.wenchou.hanyong",
  于吉: "hero.yuji.guhuo",
  荀攸: "hero.xunyou.qice",
  典韦: "hero.dianwei.guzhi-elai",
  赵云: "hero.zhaoyun.longdan",
  法正: "hero.fazheng.yiyi-dailao",
  孙策: "hero.sunce.jiangdong-bawang",
  凌统: "hero.lingtong.guoshi-zhifeng",
  吕蒙: "hero.lvmeng.baiyi-dujiang",
  公孙瓒: "hero.gongsunzan.baima-yicong",
  张郃: "hero.zhanghe.qiaobian",
  司马徽: "hero.simahui.guangshi",
  贾诩: "hero.jiaxu.fanjian",
  郭嘉: "hero.guojia.yiji-pingliao",
  张辽: "hero.zhangliao.weizhen-xiaoyao",
  马超: "hero.machao.hanqiang-pozhen",
  庞统: "hero.pangtong.niepan",
  陆逊: "hero.luxun.huoshao-lianying",
  甘宁: "hero.ganning.baiqi-jieying",
  袁术: "hero.yuanshu.yuxi",
  董卓: "hero.dongzhuo.baonue",
  华佗: "hero.huatuo.jijiu",
  曹操: "hero.caocao.jianxiong",
  荀彧: "hero.xunyu.wangzuo-zhicai",
  刘备: "hero.liubei.renze",
  诸葛亮: "hero.zhugeliang.yunchou",
  关羽: "hero.guanyu.weizhen-huaxia",
  孙权: "hero.sunquan.quanheng",
  周瑜: "hero.zhouyu.fengzhu-huoshi",
  张角: "hero.zhangjiao.wulei-hongding",
  吕布: "hero.lvbu.tianxia-wushuang",
  袁绍: "hero.yuanshao.haoling-qunxiong",
};

window.GAME_DATA.heroes.forEach((hero) => {
  hero.effectId = HERO_SKILL_EFFECT_IDS[hero.name];
});
