// 由《游戏数据速查.md》同步；该文档是具体游戏数据的唯一权威来源。
// heroes[].skill 只同步“玩家显示技能”；底层规则备注保留在权威文档中，不进入玩家界面。
window.GAME_DATA = {
  source: "游戏数据速查.md",
  heroes: [
    { name: "甄姬", faction: "魏", tier: 1, attack: 1, health: 1, skill: "[洛神] 友军被召唤时，使其 +（1）攻击力" },
    { name: "庞德", faction: "魏", tier: 1, attack: 2, health: 2, skill: "[殉节] 阵亡时，使后方最近的友军 +（2/1）" },
    { name: "黄忠", faction: "蜀", tier: 1, attack: 2, health: 3, skill: "[老当益壮] 攻击后，使自身获得（1）经验值" },
    { name: "廖化", faction: "蜀", tier: 1, attack: 2, health: 2, skill: "[宿将] 友军获得经验值时，使其 +（1）生命值" },
    { name: "马云禄", faction: "蜀", tier: 1, attack: 2, health: 2, skill: "[西凉烈女] 阵亡时，召唤1名（LV1）的骑兵" },
    { name: "诸葛瑾", faction: "吴", tier: 1, attack: 1, health: 3, skill: "[弘雅] 回合结束时，使随机1名友军 +（1/1）" },
    { name: "黄盖", faction: "吴", tier: 1, attack: 2, health: 3, skill: "[苦肉计] 受伤时，使随机（1）名敌军获得灼烧" },
    { name: "华雄", faction: "群", tier: 1, attack: 3, health: 2, skill: "[骁勇] 战斗开始时，对前方（1）名敌军造成1点伤害" },
    { name: "陈宫", faction: "群", tier: 1, attack: 1, health: 2, skill: "[百计多谋] 被招募时，对最近前方武将使用1张（1）阶计策" },
    { name: "左慈", faction: "无", tier: 1, attack: 3, health: 1, skill: "[变幻莫测] 出售时，交换前后两名（2）阶及以下武将的最终面板攻血" },

    { name: "夏侯渊", faction: "魏", tier: 2, attack: 3, health: 3, skill: "[千里奔袭] 攻击后，召唤1名LV1骑兵；其攻血为触发时夏侯渊当前攻血的（33%）" },
    { name: "于禁", faction: "魏", tier: 2, attack: 1, health: 2, skill: "[军纪严明] 回合结束时，使前方最近的（1）名武将 +1/+1" },
    { name: "魏延", faction: "蜀", tier: 2, attack: 2, health: 4, skill: "[才高气烈] 其他友军阵亡时，自身 +（1/1）" },
    { name: "马岱", faction: "蜀", tier: 2, attack: 2, health: 3, skill: "[伏斩] 回合结束时，对最近的前方友军造成（2）点伤害" },
    { name: "程普", faction: "吴", tier: 2, attack: 2, health: 3, skill: "[元勋] 被招募时，使前方最近的武将 +（1/1）" },
    { name: "小乔", faction: "吴", tier: 2, attack: 1, health: 2, skill: "[花容月貌] 前方最近的武将攻击后，使其 +（2）生命值" },
    { name: "韩当", faction: "吴", tier: 2, attack: 2, health: 4, skill: "[左右开弓] 攻击前，对随机1名有负面状态的敌军造成（3）点伤害" },
    { name: "文丑", faction: "群", tier: 2, attack: 3, health: 3, skill: "[悍勇] 最近的前方友军攻击后，自身 +（1/1）" },
    { name: "颜良", faction: "群", tier: 2, attack: 3, health: 3, skill: "[勇冠三军] 击杀后，自身 +（2/2）" },
    { name: "貂蝉", faction: "无", tier: 2, attack: 2, health: 1, skill: "[倾城] 攻击后，使随机（1）名敌军获得反间" },

    { name: "夏侯惇", faction: "魏", tier: 3, attack: 3, health: 5, skill: "[刚勇] 受伤时，使最近的后方友军 +（2/2）" },
    { name: "乐进", faction: "魏", tier: 3, attack: 3, health: 3, skill: "[先登陷阵] 阵亡时，使最前方友军 +（4/4）" },
    { name: "徐晃", faction: "魏", tier: 3, attack: 4, health: 4, skill: "[长驱直入] 最近的前方友军攻击后，对最后方敌军造成（3）点伤害" },
    { name: "张飞", faction: "蜀", tier: 3, attack: 4, health: 4, skill: "[燕人咆哮] 战斗开始时，使最前方（1）名敌军获得破胆" },
    { name: "徐庶", faction: "蜀", tier: 3, attack: 3, health: 3, skill: "[荐才] 战斗开始时，使前方最近的武将获得（1）经验值" },
    { name: "太史慈", faction: "吴", tier: 3, attack: 5, health: 3, skill: "[箭无虚发] 战斗开始时，对生命值最高的敌军造成（3）点伤害和灼烧" },
    { name: "周泰", faction: "吴", tier: 3, attack: 3, health: 3, skill: "[肉身铁壁] 攻击时，受到的普通伤害减少（3）点" },
    { name: "鲁肃", faction: "吴", tier: 3, attack: 3, health: 3, skill: "[联合] 回合开始时，每存在2个阵容羁绊，获得（2）金币" },
    { name: "汉献帝", faction: "群", tier: 3, attack: 2, health: 1, skill: "[飘摇] 阵亡时，使随机1名友军获得诏书" },
    { name: "于吉", faction: "无", tier: 3, attack: 3, health: 2, skill: "[蛊惑] 阵亡时，在原位置召唤1名（LV1）的方士；方士阵亡时，使随机友军 +（3/3）" },

    { name: "荀攸", faction: "魏", tier: 4, attack: 4, health: 2, skill: "[奇策] 使用计策时，使周围友军 +（1/1）" },
    { name: "典韦", faction: "魏", tier: 4, attack: 6, health: 6, skill: "[古之恶来] 战斗开始时，吞噬前方最近的友军，并在阵亡后将其以（LV1）释放" },
    { name: "赵云", faction: "蜀", tier: 4, attack: 6, health: 6, skill: "[龙胆] 升级时，获得无双，并使自己 +（2/2）" },
    { name: "法正", faction: "蜀", tier: 4, attack: 4, health: 3, skill: "[以逸待劳] 战斗开始时，使最近的后方友军获得（1）经验值和休整；休整使其在友军攻击时自身 +（2）生命值，获得负面状态时清除自身与负面状态" },
    { name: "孙策", faction: "吴", tier: 4, attack: 5, health: 5, skill: "[江东霸王] 战斗开始时，每存在1名其他自身羁绊武将，自身 +（1/2）" },
    { name: "凌统", faction: "吴", tier: 4, attack: 4, health: 4, skill: "[国士之风] 自身羁绊武将被招募时，使其 +（1/2）" },
    { name: "吕蒙", faction: "吴", tier: 4, attack: 4, health: 5, skill: "[白衣渡江] 攻击前，使最前方（1）名敌军的技能在本轮无法触发" },
    { name: "董卓", faction: "群", tier: 4, attack: 6, health: 4, skill: "[暴虐] 回合结束时，击杀随机1名非自身羁绊武将；成功击杀后使自己 +（2/2）" },
    { name: "张郃", faction: "群", tier: 4, attack: 4, health: 4, skill: "[巧变] 阵亡时，随机召唤1名与张郃至少共享一个羁绊的正式武将" },
    { name: "司马徽", faction: "无", tier: 4, attack: 3, health: 3, skill: "[广识] 每次购买司马徽时，选择1名其他友军，为其添加1个额外羁绊" },

    { name: "贾诩", faction: "魏", tier: 5, attack: 4, health: 3, skill: "[反间] 战斗开始时，使随机（1）名敌军获得反间" },
    { name: "郭嘉", faction: "魏", tier: 5, attack: 5, health: 2, skill: "[遗计平辽] 阵亡时，使所有自身羁绊武将 +（2/2）" },
    { name: "张辽", faction: "魏", tier: 5, attack: 7, health: 5, skill: "[威震逍遥] 战斗开始时，使敌军全体当前生命值 -（20%）" },
    { name: "马超", faction: "蜀", tier: 5, attack: 7, health: 5, skill: "[破阵] 首次攻击时，本次普通攻击额外造成自身攻击力（100%）的伤害" },
    { name: "庞统", faction: "蜀", tier: 5, attack: 5, health: 4, skill: "[铁索连环] 战斗开始时，使随机（2）名敌军获得连锁" },
    { name: "陆逊", faction: "吴", tier: 5, attack: 5, health: 6, skill: "[火烧连营] 攻击后，对所有灼烧敌军造成自身攻击力（20%）的伤害" },
    { name: "甘宁", faction: "吴", tier: 5, attack: 7, health: 5, skill: "[百骑劫营] 战斗开始时，对最后方敌军依次施加（2）次灼烧" },
    { name: "袁术", faction: "群", tier: 5, attack: 5, health: 3, skill: "[玉玺] 被召唤时获得并佩戴传国玉玺；自身佩戴时，玉玺效果额外触发（1）次" },
    { name: "公孙瓒", faction: "群", tier: 5, attack: 6, health: 4, skill: "[白马义从] 阵亡后，召唤1名（LV1）的白马义从；白马义从4/4，攻击前对生命值最低的敌军造成（4）点伤害" },
    { name: "华佗", faction: "无", tier: 5, attack: 3, health: 3, skill: "[急救] 前方最近的友军阵亡时，使其以LV2、3/3复活；每回合生效（1）次" },

    { name: "曹操", faction: "魏", tier: 6, attack: 6, health: 6, skill: "[奸雄] 自身羁绊武将阵亡时，使随机1名其他友军 +（4/4）" },
    { name: "荀彧", faction: "魏", tier: 6, attack: 5, health: 3, skill: "[王佐之才] 自身羁绊武将被召唤时，使其 +（4/4）" },
    { name: "刘备", faction: "蜀", tier: 6, attack: 7, health: 7, skill: "[仁泽] 自身羁绊武将被召唤时，使其获得（1）经验值" },
    { name: "诸葛亮", faction: "蜀", tier: 6, attack: 5, health: 5, skill: "[运筹] 友军攻击后，对随机1名敌军造成（4）点伤害" },
    { name: "关羽", faction: "蜀", tier: 6, attack: 10, health: 8, skill: "[威震华夏] 攻击后，使最前方（1）名敌军获得震慑" },
    { name: "孙权", faction: "吴", tier: 6, attack: 5, health: 5, skill: "[权衡] 回合结束时，使前方最近的自身羁绊武将 +（5）攻击力，使后方最近的自身羁绊武将 +（5）生命值" },
    { name: "周瑜", faction: "吴", tier: 6, attack: 8, health: 6, skill: "[风助火势] 敌军受到的负面状态数值效果增加（1）倍" },
    { name: "张角", faction: "群", tier: 6, attack: 10, health: 3, skill: "[五雷轰顶] 战斗开始时，对随机敌军造成自身攻击力（10%）的伤害，触发5次" },
    { name: "吕布", faction: "群", tier: 6, attack: 12, health: 10, skill: "[天下无双] 攻击前，使自己获得（1）倍效果的无双" },
    { name: "袁绍", faction: "群", tier: 6, attack: 5, health: 5, skill: "[号令群雄] 自身羁绊武将被招募时，使所有友军 +（1/2）" },
  ],
  items: [
    { name: "演练", category: "计策", targetMode: "unit", tier: 1, cost: 3, skill: "选择1个武将 +1/+1", effectId: "stratagem.encourage", image: "res/item_icon/stratagem-encourage.png" },
    { name: "口才", category: "计策", targetMode: "unit", tier: 1, cost: 2, skill: "选择1个武将添加1个额外羁绊，持续1回合", effectId: "stratagem.temporary-bond", image: "res/item_icon/stratagem-temporary-bond.png" },
    { name: "令箭", category: "装备", tier: 2, cost: 1, skill: "相同触发条件的武将技能优先触发；东吴业火仍以最高优先级先行结算", effectId: "equipment.initiative-flag", image: "res/item_icon/equipment-initiative-flag.png" },
    { name: "兵符", category: "装备", tier: 2, cost: 3, skill: "阵亡后，在己方最前方召唤1名2/1骑兵", effectId: "equipment.cavalry-talisman", image: "res/item_icon/equipment-cavalry-talisman.png" },
    { name: "举贤", category: "计策", targetMode: "lineup", tier: 2, cost: 3, skill: "人数最多的已激活羁绊中，使随机1名武将 +2/+2；并列时随机选择1个羁绊", effectId: "stratagem.recommend-talent", image: "res/item_icon/stratagem-recommend-talent.png" },
    { name: "绝影", category: "装备", tier: 3, cost: 3, skill: "受到的伤害 -2", effectId: "equipment.iron-armor", image: "res/item_icon/equipment-iron-armor.png" },
    { name: "诏书", category: "装备", tier: 3, generatedOnly: true, skill: "抵挡最多10点伤害，或阻止1次负面状态并清空状态槽；生效后消失", effectId: "equipment.imperial-edict", image: "res/item_icon/zhaoshu.png" },
    { name: "同袍共进", category: "计策", targetMode: "lineup", tier: 3, cost: 3, skill: "人数最多的已激活羁绊中，使最前方2名武将 +1/+1；并列时随机选择1个羁绊", effectId: "stratagem.advance-together", image: "res/item_icon/stratagem-advance-together.png" },
    { name: "潜龙蓄势", category: "计策", targetMode: "lineup", tier: 3, cost: 3, skill: "使未激活羁绊中的所有武将 +2/+2", effectId: "stratagem.hidden-potential", image: "res/item_icon/stratagem-hidden-potential.png" },
    { name: "铁盾", category: "装备", tier: 4, cost: 3, skill: "抵挡10点伤害，生效1次", effectId: "equipment.iron-shield", image: "res/item_icon/equipment-iron-shield.png" },
    { name: "整军经武", category: "计策", targetMode: "lineup", tier: 4, cost: 3, skill: "选择1个羁绊，使商店中该羁绊下所有武将 +2/+2", effectId: "stratagem.train-army", image: "res/item_icon/stratagem-train-army.png" },
    { name: "鼓舞", category: "计策", targetMode: "unit", tier: 4, cost: 3, skill: "选择1个武将 +3/+3", effectId: "stratagem.blood-oath", image: "res/item_icon/stratagem-inspire.png" },
    { name: "神农秘典", category: "装备", tier: 5, cost: 3, skill: "获得负面状态或受伤时使自身 +2/+2", effectId: "equipment.blood-armor", image: "res/item_icon/equipment-blood-armor.png" },
    { name: "传国玉玺", category: "装备", tier: 5, generatedOnly: true, skill: "阵亡时，使商店中自身羁绊武将永久 +1/+1", effectId: "equipment.imperial-jade-seal", image: "res/item_icon/equipment-imperial-jade-seal.png" },
    { name: "同心戮力", category: "计策", targetMode: "lineup", tier: 5, cost: 3, skill: "使人数最多的已激活羁绊下所有武将 +1/+2；并列时随机选择1个羁绊", effectId: "stratagem.united-force", image: "res/item_icon/stratagem-united-force.png" },
    { name: "开悟", category: "计策", targetMode: "unit", tier: 5, cost: 3, skill: "选择1个武将，经验值 +1", effectId: "stratagem.master-guidance", image: "res/item_icon/stratagem-master-guidance.png" },
    { name: "蚩尤古盾", category: "装备", tier: 6, cost: 3, skill: "抵挡10伤害，生效2次", effectId: "equipment.black-tortoise-shield", image: "res/item_icon/equipment-black-tortoise-shield.png" },
    { name: "修罗刀", category: "装备", tier: 6, cost: 3, skill: "攻击伤害 +20，生效1次", effectId: "equipment.siege-crossbow", image: "res/item_icon/equipment-siege-crossbow.png" },
    { name: "聚势强军", category: "计策", targetMode: "unit", tier: 6, cost: 3, skill: "选择1个武将 +4/+4；每次使用后，下一次额外 +1/+1", effectId: "stratagem.gather-strength", image: "res/item_icon/stratagem-gather-strength.png" },
    { name: "帅印", category: "装备", tier: 1, cost: 0, rewardOnly: true, purpleStars: true, skill: "己方武将被召唤时，使其 +1/+1", effectId: "equipment.commander-seal", image: "res/item_icon/equipment-commander-seal.png" },
    { name: "虎符", category: "装备", tier: 1, cost: 0, rewardOnly: true, purpleStars: true, skill: "战斗开始时，使自身 +3/+3 与1经验值", effectId: "equipment.tiger-tally", image: "res/item_icon/equipment-tiger-tally.png" },
    { name: "百厄角", category: "装备", tier: 1, cost: 0, rewardOnly: true, purpleStars: true, skill: "攻击后，对敌方最前方单位施加1种随机负面状态", effectId: "equipment.calamity-blade", image: "res/item_icon/equipment-calamity-blade.png" },
    { name: "龙方壶", category: "装备", tier: 1, cost: 0, rewardOnly: true, purpleStars: true, skill: "回合结束时，若阵容中无激活的羁绊，使自身永久 +2/+2", effectId: "equipment.dragon-square-pot", image: "res/item_icon/equipment-dragon-square-pot.png" },
    { name: "白玉龟", category: "装备", tier: 2, cost: 0, rewardOnly: true, skill: "获得负面状态时，将其清除并使自身 +2/+2", effectId: "equipment.white-jade-turtle", image: "res/item_icon/equipment-white-jade-turtle.png" },
    { name: "阎魔帆", category: "装备", tier: 2, cost: 0, rewardOnly: true, skill: "阵亡后，以5/5复活并继承携带者等级；复活后无装备和状态", effectId: "equipment.yanmo-sail", image: "res/item_icon/equipment-yanmo-sail.png" },
    { name: "筹措军资", category: "计策", targetMode: "lineup", tier: 2, cost: 0, rewardOnly: true, skill: "获得12金币", effectId: "reward.military-funds", image: "res/item_icon/stratagem-military-funds.png" },
    { name: "厉兵秣马", category: "计策", targetMode: "lineup", tier: 2, cost: 0, rewardOnly: true, skill: "获得2张免费的聚势强军", effectId: "reward.ready-army", image: "res/item_icon/stratagem-ready-army.png" },
    { name: "众志成城", category: "计策", targetMode: "lineup", tier: 3, cost: 0, rewardOnly: true, skill: "使我军人数最多的羁绊解锁5人效果；并列时选择1个", effectId: "reward.united-bond", image: "res/item_icon/stratagem-united-bond.png" },
    { name: "合纵连横", category: "计策", targetMode: "lineup", tier: 3, cost: 0, rewardOnly: true, skill: "获得3份盟书", effectId: "reward.alliance-pacts", image: "res/item_icon/stratagem-alliance-pacts.png" },
    { name: "方天画戟", category: "装备", tier: 3, cost: 0, rewardOnly: true, skill: "攻击时，额外造成自身攻击力30%的伤害，并在本次同时攻击阶段减少同等伤害；结果向下取整", effectId: "equipment.fangtian-halberd", image: "res/item_icon/equip_fangtianhuaji.png" },
    { name: "黄天令旗", category: "装备", tier: 3, cost: 0, rewardOnly: true, skill: "携带者的每个技能伤害实例额外附加自身攻击力20%的伤害；结果向下取整", effectId: "equipment.yellow-heaven-banner", image: "res/item_icon/equipment-yellow-heaven-banner.png" },
    { name: "盟书", category: "计策", targetMode: "unit", tier: 3, cost: 0, rewardOnly: true, generatedOnly: true, skill: "选择1名武将，为其添加1个本局永久额外羁绊", effectId: "reward.alliance-scroll", image: "res/item_icon/strat_junlve.png" },
  ],
};

// 稳定的结构化武将技能 ID。技能描述只负责展示，实际结算由 app.js 的效果定义驱动。
const HERO_SKILL_EFFECT_IDS = {
  甄姬: "hero.zhenji.luoshen",
  庞德: "hero.pangde.xunjie",
  黄忠: "hero.huangzhong.laodang-yizhuang",
  廖化: "hero.liaohua.sujiang",
  马云禄: "hero.mayunlu.xiliang-lienv",
  诸葛瑾: "hero.zhugejin.hongya",
  黄盖: "hero.huanggai.kurouji",
  华雄: "hero.huaxiong.xiaoyong",
  陈宫: "hero.chengong.baiji-duomou",
  左慈: "hero.zuoci.bianhuan-moce",
  夏侯渊: "hero.xiahouyuan.qianli-benxi",
  于禁: "hero.yujin.junji-yanming",
  魏延: "hero.weiyan.caigao-qilie",
  马岱: "hero.madai.fuzhan",
  程普: "hero.chengpu.yuanxun",
  小乔: "hero.xiaoqiao.huaron-yuemao",
  韩当: "hero.handang.zuoyou-kaigong",
  文丑: "hero.wenchou.yongguan-sanjun",
  汉献帝: "hero.hanxiandi.piaoyao",
  貂蝉: "hero.diaochan.qingcheng",
  夏侯惇: "hero.xiahoudun.gangyong",
  乐进: "hero.yuejin.xiandeng-xianzhen",
  徐晃: "hero.xuhuang.changqu-zhiru",
  张飞: "hero.zhangfei.yanren-paoxiao",
  徐庶: "hero.xushu.jiancai",
  太史慈: "hero.taishici.jianwu-xufa",
  周泰: "hero.zhoutai.roushen-tiebi",
  鲁肃: "hero.lusu.lianhe",
  颜良: "hero.yanliang.yongguan-sanjun",
  于吉: "hero.yuji.guhuo",
  荀攸: "hero.xunyou.qice",
  典韦: "hero.dianwei.guzhi-elai",
  赵云: "hero.zhaoyun.longdan",
  法正: "hero.fazheng.yiyi-dailao",
  孙策: "hero.sunce.jiangdong-bawang",
  凌统: "hero.lingtong.guoshi-zhifeng",
  吕蒙: "hero.lvmeng.baiyi-dujiang",
  董卓: "hero.dongzhuo.baonue",
  张郃: "hero.zhanghe.qiaobian",
  司马徽: "hero.simahui.guangshi",
  贾诩: "hero.jiaxu.fanjian",
  郭嘉: "hero.guojia.yiji-pingliao",
  张辽: "hero.zhangliao.weizhen-xiaoyao",
  马超: "hero.machao.pozhen",
  庞统: "hero.pangtong.tiesuo-lianhuan",
  陆逊: "hero.luxun.huoshao-lianying",
  甘宁: "hero.ganning.baiqi-jieying",
  袁术: "hero.yuanshu.yuxi",
  公孙瓒: "hero.gongsunzan.baima-yicong",
  华佗: "hero.huatuo.jijiu",
  曹操: "hero.caocao.jianxiong",
  荀彧: "hero.xunyu.wangzuo-zhicai",
  刘备: "hero.liubei.renze",
  诸葛亮: "hero.zhugeliang.yunchou",
  关羽: "hero.guanyu.weizhen-huaxia",
  孙权: "hero.sunquan.quanheng",
  周瑜: "hero.zhouyu.fengzhu-huoshi",
  张角: "hero.zhangjiao.wulei-hongding",
  吕布: "hero.lvbu.tianxia-wushuang",
  袁绍: "hero.yuanshao.haoling-qunxiong",
};

window.GAME_DATA.heroes.forEach((hero) => {
  hero.effectId = HERO_SKILL_EFFECT_IDS[hero.name];
});
