[CmdletBinding()]
param(
  [string]$SourceDirectory,
  [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($SourceDirectory)) {
  $SourceDirectory = Join-Path $PSScriptRoot "..\opponent-data"
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
  $OutputPath = Join-Path $PSScriptRoot "..\opponent-data\opponent-data.js"
}

$utf8 = [System.Text.UTF8Encoding]::new($false)
$resolvedSource = [System.IO.Path]::GetFullPath($SourceDirectory)
$resolvedOutput = [System.IO.Path]::GetFullPath($OutputPath)

if (-not [System.IO.Directory]::Exists($resolvedSource)) {
  throw "Opponent data directory does not exist: $resolvedSource"
}

$files = @(
  Get-ChildItem -LiteralPath $resolvedSource -Filter "*.json" -File |
    Sort-Object Name
)

if ($files.Count -lt 4) {
  throw "Opponent pool requires at least 4 complete JSON files; found $($files.Count)."
}

$entries = [System.Collections.Generic.List[object]]::new()
$sessionIds = [System.Collections.Generic.HashSet[string]]::new(
  [System.StringComparer]::Ordinal
)
$requiredRounds = 1..20

foreach ($file in $files) {
  $raw = [System.IO.File]::ReadAllText($file.FullName, $utf8)
  try {
    $session = $raw | ConvertFrom-Json
  } catch {
    throw "Failed to parse JSON: $($file.FullName)`n$($_.Exception.Message)"
  }

  if ($session.schemaVersion -ne 1) {
    throw "$($file.Name): schemaVersion must be 1."
  }
  if ($session.status -ne "completed") {
    throw "$($file.Name): status must be completed."
  }
  if ([string]::IsNullOrWhiteSpace([string]$session.id)) {
    throw "$($file.Name): missing unique id."
  }
  if (-not $sessionIds.Add([string]$session.id)) {
    throw "$($file.Name): duplicate session id $($session.id)."
  }

  $roundNumbers = @(
    $session.rounds |
      ForEach-Object { [int]$_.round } |
      Sort-Object -Unique
  )
  $missingRounds = @($requiredRounds | Where-Object { $_ -notin $roundNumbers })
  if ($missingRounds.Count -gt 0) {
    throw "$($file.Name): missing rounds $($missingRounds -join ",")."
  }

  $sourceRounds = @($session.rounds | Where-Object { $_.round -in $requiredRounds })
  if ($sourceRounds.Count -ne $requiredRounds.Count) {
    throw "$($file.Name): rounds 1-20 must appear exactly once."
  }
  foreach ($round in $sourceRounds) {
    if (-not ($round.lineup -is [System.Array]) -or $round.lineup.Count -ne 5) {
      throw "$($file.Name): round $($round.round) must contain 5 lineup slots."
    }
  }

  $runtimeRounds = @(
    $sourceRounds |
      Sort-Object round |
      ForEach-Object {
        [pscustomobject]@{
          round = [int]$_.round
          recordedAt = $_.recordedAt
          lineup = $_.lineup
          bonds = $_.bonds
        }
      }
  )
  $entries.Add([pscustomobject]@{
    key = [string]$session.id
    label = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    fileName = $file.Name
    session = [pscustomobject]@{
      schemaVersion = 1
      id = [string]$session.id
      status = "completed"
      startedAt = $session.startedAt
      completedAt = $session.completedAt
      rounds = $runtimeRounds
    }
  })
}

$payload = ConvertTo-Json -InputObject $entries -Depth 100 -Compress
$content = @"
/* Generated by scripts/build-opponent-pool.ps1. Do not edit manually. */
window.OPPONENT_DATA_POOL = $payload;
"@

$outputDirectory = [System.IO.Path]::GetDirectoryName($resolvedOutput)
[System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
[System.IO.File]::WriteAllText($resolvedOutput, $content, $utf8)

Write-Host "Generated opponent pool: $resolvedOutput"
Write-Host "Valid entries: $($entries.Count)"
